name: CI/CD - Azure Deploy Docker

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: tiagofarsonisiemann/fire-alarm-app:latest

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build com Maven
        run: mvn clean package -DskipTests

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.tiagofarsonisiemann }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE }} .

      - name: Push para Docker Hub
        run: docker push ${{ env.DOCKER_IMAGE }}

      - name: Deploy para Azure Web App
        uses: azure/webapps-container-deploy@v1
        with:
          app-name: 'fire-alarm-app'
          images: ${{ env.DOCKER_IMAGE }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}